POST http://localhost:8100/api/task
Content-Type: application/json

{
    "taskName" : "Do grocery",
    "taskDescription": "Buy milk, bread, eggs, and fruits",
    "startDate" : "2023-05-25T12:34",
    "endDate" : "2023-05-28T12:34"
}

###

POST http://localhost:8100/api/task
Content-Type: application/json

{
    "taskName" : "Money",
    "taskDescription": "Buy milk, bread, eggs, and fruits",
    "startDate" : "2023-05-25T12:34",
    "endDate" : "2023-05-28T12:34"
}

###

POST http://localhost:8100/api/task
Content-Type: application/json

{
    "taskName" : "Money Maker",
    "taskDescription": "Buy milk, bread, eggs, and fruits",
    "startDate" : "2023-05-25T12:34",
    "endDate" : "2023-05-28T12:34"
}

###

GET  http://localhost:8100/api/tasks
Content-Type: application/json

###

PUT http://localhost:8100/api/task/Money
Content-Type: application/json

{
    "taskName" : "Money Update",
    "taskDescription": "Buy",
    "endDate" : "2025-05-28T12:34"
}

###

DELETE  http://localhost:8100/api/task/Money Update
Content-Type: application/json

###

POST http://localhost:8100/createProject
Content-Type: application/json

{
    "projectName" : "Build An Android App"
}

###

POST http://localhost:8100/createProject
Content-Type: application/json

{
    "projectName" : "Dance like Hrithik Roshan"
}

###

DELETE  http://localhost:8100/deleteProject/Build An Android App
Content-Type: application/json

###

GET  http://localhost:8100/api/projects
Content-Type: application/json
